

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkpuhinyelffnssjpidl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrcHVoaW55ZWxmZm5zc2pwaWRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MTY3NDYsImV4cCI6MjA2MDA5Mjc0Nn0.AoZ6rUfe0NLCFvrabjXeJ00-rNWNfW6DDPWQuOmYgRU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
    }
  }
);
